#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

logging:
  level:
     com.daybreak.gateway.dao : debug

server:
  port: 8032
spring:
  application:
    name: gateway
  resources:
    static-locations: classpath:/static
  datasource:
#修改此处：修改数据库、账号、密码3项
    url: jdbc:mysql://127.0.0.1:3306/spring_gateway_security?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: userName111
    password: passWord111
#    driverClassName: com.mysql.jdbc.Driver
#修改此处：请在自己机子上安装redis，并修改下面配置信息
  redis:
    database: 0
    host: localhost
    port: 6379
#    password: 123456
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  cloud:
    gateway:
      discovery:
        locator:
        # 是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
        # 为true,自动创建路由,路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: true
          #lowerCaseServiceId: true  设置微服务应用名小写访问
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            exposedHeaders: "Access-Control-Allow-Origin"
#        cors-configurations:
#          '[/**]':
#            allow-credentials: true
#            allowed-origins: "*"
#            allowed-methods: "*"
#            allowed-headers: "*"
#            exposed-headers: "Access-Control-Allow-Origin"
#            max-age: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/


mybatis:

    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

